system:
  addr: localhost:10002
  host: http://localhost:10002
  root: "/home/convee/go/src/goblog"
  cdn: "http://localhost:10002/static"
log:
  stderr: true
  level: debug

redis:
  addr: "127.0.0.1:6379"
  max_idle: 10
  max_active: 1
  max_idle_timeout: 1

mysql:
  ip: "127.0.0.1"
  port: "3306"
  username: "convee"
  password: "TMd6kQ0fayHZewqFUjX8."
  database: "blog"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 20
  max_lifetime: 600
es:
  urls: "http://127.0.0.1:9200"
