system:
  addr: localhost:9090
  host: http://convee.cn
  root: "/data/module/blog"
  cdn: "http://convee.cn/static"
log:
  stderr: true
  level: debug

redis:
  addr: "127.0.0.1:6379"
  max_idle: 10
  max_active: 1
  max_idle_timeout: 1

mysql:
  ip: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "VWhOsYX5ou1xfTb2"
  database: "blog"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 20
  max_lifetime: 600
es:
  urls: "http://127.0.0.1:9200"
